# Generated by Django 2.1.8 on 2019-07-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_goods_goods_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_status',
            field=models.IntegerField(default=1, verbose_name='商品状态'),
        ),
    ]
