# Generated by Django 2.1.8 on 2019-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20190725_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_image',
            field=models.ImageField(upload_to='store/images', verbose_name='商品图片'),
        ),
    ]
